# Generated by Django 4.0 on 2022-12-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_account_email_verified_alter_account_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
