# Generated by Django 4.0 on 2022-11-12 14:26

import apps.company.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250, verbose_name="company name")),
                (
                    "about",
                    models.TextField(
                        blank=True, default="No about", max_length=500, null=True, verbose_name="company information"
                    ),
                ),
                ("email", models.EmailField(max_length=60, verbose_name="company email address")),
                (
                    "number",
                    models.CharField(
                        blank=True, default="No number", max_length=60, null=True, verbose_name="company phone number"
                    ),
                ),
                ("address", models.CharField(default="No Address", max_length=250, verbose_name="company address")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, null=True, unique=True, verbose_name="company safe URL"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, max_length=255, null=True, upload_to=apps.company.utils.get_avatar_filepath
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="format: Y-m-d H:M:S", verbose_name="company visibility"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="format: Y-m-d H:M:S", verbose_name="date company created"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="company_account",
                        to="account.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
    ]
