# Generated by Django 4.0 on 2022-11-14 13:54

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "invoice_code",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Automaticlly generated",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Invoice Code/Id",
                    ),
                ),
                ("client_name", models.CharField(max_length=250, verbose_name="Client Name")),
                (
                    "client_email",
                    models.EmailField(help_text="Must be work", max_length=250, verbose_name="Client Email Address"),
                ),
                (
                    "client_number",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Client Phone Number"),
                ),
                (
                    "client_address",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Client Full Adress"),
                ),
                (
                    "client_zipcode",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Client Adress's Zipcode"),
                ),
                ("client_city", models.CharField(blank=True, max_length=50, null=True, verbose_name="Client City")),
                (
                    "client_country",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Client Country"),
                ),
                ("due_after", models.IntegerField(help_text="shouold be integer", verbose_name="Due after")),
                ("email_is_sent", models.BooleanField(default=False, verbose_name="Email Is sent")),
                ("is_paid", models.BooleanField(default=False, verbose_name="Invoice Is paid")),
                (
                    "discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        null=True,
                        verbose_name="Discount amount",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="format: Y-m-d H:M:S", verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="format: Y-m-d H:M:S", verbose_name="Updated at"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="company.company",
                        verbose_name="Issuing company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_invoices",
                        to="account.account",
                        verbose_name="Created By",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modified_invoices",
                        to="account.account",
                        verbose_name="Modified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=255, null=True, verbose_name="Item's title/name")),
                ("quantity", models.IntegerField(default=0, verbose_name="Item's quantity")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=6, verbose_name="Item's price per one"
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        blank=True, decimal_places=1, default=0, max_digits=3, null=True, verbose_name="Tax rate"
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Automaticlly generated",
                        max_digits=6,
                        null=True,
                        verbose_name="Total amount after taxes",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="invoice.invoice",
                        verbose_name="Invoice",
                    ),
                ),
            ],
        ),
    ]
