# Generated by Django 4.0 on 2022-11-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="description",
            field=models.TextField(blank=True, default="no description", null=True),
        ),
    ]
