# Generated by Django 4.0 on 2022-11-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0002_invoice_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="is_paid",
        ),
        migrations.AddField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[("paid", "paid"), ("pending", "pending")],
                default="pending",
                max_length=20,
                verbose_name="Invoice Status",
            ),
        ),
    ]
